Update NU1105.md
NuGet/docs.microsoft.com-nuget pull request #2409
Opened 2021-04-26 17:22 UTC by rpanday

Added sample code to restore projects in solution using dotnet CLI

#2340

2021-04-26 17:23 UTC, opbld34 commented
Docs Build status updates of commit _[d99d96f](https://github.com/rpanday/docs.microsoft.com-nuget/commits/d99d96f95d95be3ea7069942303de33de9d94ab8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/errors-and-warnings/NU1105.md](https://github.com/rpanday/docs.microsoft.com-nuget/blob/patch-2/docs/reference/errors-and-warnings/NU1105.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1105?branch=pr-en-us-2409) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C26%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202104261722335349-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N0xSBi60U%2FZIoMuaWVuGffRw%2FZ2rTn3aV4l6KLhoz6g%3D&st=2021-04-26T17%3A18%3A05Z&se=2021-05-27T17%3A23%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/19a7edc0-f91d-0fd5-6e5f-4d131db05c11?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 16:01 UTC, JonDouglas requested changes
Thanks for your contribution! Can we move this sample into the "Command Line" section?

![image](https://user-images.githubusercontent.com/1288848/116273988-dbf95800-a747-11eb-947b-87e518010896.png)

2021-04-28 13:57 UTC, opbld32 commented
Docs Build status updates of commit _[df8bfe8](https://github.com/rpanday/docs.microsoft.com-nuget/commits/df8bfe875ccb30df6a702a30f19350495e2ef3f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/errors-and-warnings/NU1105.md](https://github.com/rpanday/docs.microsoft.com-nuget/blob/patch-2/docs/reference/errors-and-warnings/NU1105.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1105?branch=pr-en-us-2409) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C19a7edc0-f91d-0fd5-6e5f-4d131db05c11%5CPullRequest%5C202104281357096847-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BHlurHPBLN77xfn%2B4vMoBhG%2F4eYM2tUvZE8%2BqbVZQbU%3D&st=2021-04-28T13%3A52%3A47Z&se=2021-05-29T13%3A57%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/19a7edc0-f91d-0fd5-6e5f-4d131db05c11?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 05:29 UTC, rpanday commented
@JonDouglas can you please review? I've addressed comments.

2021-05-06 13:14 UTC, JonDouglas approved these changes
Thank you so much for your contribution!

2021-05-06 13:15 UTC, merged