Clarify what a package being available means
NuGet/docs.microsoft.com-nuget pull request #3360
Opened 2024-11-18 23:36 UTC by nkolev92

See motivation: https://github.com/NuGet/Home/issues/13930#issuecomment-2484174618. 

tldr; If a package content resource lists a package as available, it should be able to download. 
Being unavailable breaks the contract.

2024-11-18 23:44 UTC, erdembayar approved these changes

2024-11-18 23:46 UTC, donnie-msft requested changes

2024-11-18 23:46 UTC, donnie-msft commented on docs/api/package-base-address-resource.md
> +client can construct a predictable URL to enumerate all package versions. Every version listen in this list must be available for download.
```suggestion
client can construct a predictable URL to enumerate all package versions. Every version listed in this list must be available for download.
```

2024-11-19 00:22 UTC, martinrrm approved these changes

2024-11-19 16:13 UTC, donnie-msft approved these changes

2024-11-19 16:50 UTC, zivkan approved these changes

2024-11-19 17:50 UTC, merged